server:
  #服务端口号
  port: 8090
  servlet:
    context-path: /admin
spring:
  profiles:
    #默认开发环境
    active: dev
  servlet:
    multipart:
      #开启文件上传
      enabled: true
      #最大支持单个文件大小
      max-file-size: 10MB
      #最大请求大小
      max-request-size: 10MB

#mybatis相关配置
mybatis:
  mapper-locations: classpath*:mybatis/*/*-mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#JWT相关配置
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: education-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

#安全路径白名单
secure:
  ignored:
    urls:
    - /doc.html
    - /webjars/**
    - /swagger-ui/index.html
    - /swagger-ui/**
    - /swagger-resources/**
    - /swagger/**
    - /v2/api-docs
    - /v3/api-docs
    - /webjars/springfox-swagger-ui/**
    - /actuator/**
    - /druid/**
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /userManage/login.do

